<a href="https://colab.research.google.com/github/DevSecOps-Stack/ML-Prerequisites/blob/main/ml_beginner_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [1]:
import numpy as np

array of zeros

In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array of ones

In [ ]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array of particular value

In [ ]:
z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


identity matrix

In [ ]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


create a numpy array with random values with floating values

In [ ]:
b = np.random.random((3,4))
print(b)

[[0.14833147 0.01144511 0.26078043 0.5793363 ]
 [0.87165065 0.52476911 0.84878946 0.41335203]
 [0.22623399 0.42088161 0.68389723 0.16473441]]


create a numpy array with random values without floating values

In [ ]:
c = np.random.randint(1,10,(3,4))
print(c)

[[2 8 9 9]
 [6 3 1 6]
 [3 7 6 8]]


create array evenly spaces values

In [ ]:
d = np.linspace(1,10,6)
print(d)

[ 1.   2.8  4.6  6.4  8.2 10. ]


np.linspace(1, 10, 6):

This function creates a list of numbers starting from 1 and ending at 10.
It will create exactly 6 numbers, and these numbers will be evenly spread out between 1 and 10.
For example, if you want to go from 1 to 10 and stop at 6 points along the way, you get numbers that are evenly spaced.

print(d):

This command shows you the list of numbers that were created in the step above. note : above example starts with 1 and adds 1.8 till 10.

array of evenly spaces values specifying the step

In [ ]:
e = np.arange(1,10,2)
print(e)

[1 3 5 7 9]


Creating an Array with np.arange():

np.arange(start, stop, step) is a function that generates a sequence of numbers within a specified range.
start: The first value in the sequence (here, it's 1).
stop: The upper bound of the sequence (here, it's 10). The sequence will not include this value.
step: The difference between consecutive numbers in the sequence (here, it's 2).
So, np.arange(1, 10, 2) creates an array containing the numbers: 1, 3, 5, 7, and 9.

Storing the Array: The resulting array is stored in the variable e.

Printing the Array: The line print(e) displays the contents of the array e on the console.

convert a list of numpy array

In [ ]:
list_2 = [1,2,3,4]
np_array_2 = np.asarray(list_2)
print(np_array_2)
type(np_array_2)

[1 2 3 4]


numpy.ndarray

analysing the numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.shape)
print(c.ndim)

[[21 39 70 31 20]
 [55 83 40 68 31]
 [37 38 76 14 81]
 [61 44 29 47 44]
 [87 21 41 58 57]]
(5, 5)
2


number of elements in an array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.size)

[[79 51 82 43 31]
 [80 38 29 38 65]
 [87 64 66 73 32]
 [70 10 24 13 84]
 [51 38 56 30 40]]
25


checking the datatypes of values in the array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.dtype)

[[69 21 18 26 31]
 [67 37 77 60 10]
 [75 11 47 61 57]
 [42 82 64 89 51]
 [42 54 87 85 49]]
int64


math operations

In [ ]:
list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]
print(list_1 + list_2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 7 4]
 [3 4 1]
 [6 3 6]]
[[14 15 14]
 [16 12 17]
 [13 19 18]]


In [ ]:
print(a+b)

[[15 22 18]
 [19 16 18]
 [19 22 24]]


In [ ]:
print(a-b)

[[-13  -8 -10]
 [-13  -8 -16]
 [ -7 -16 -12]]


In [ ]:
print(a*b)

[[ 14 105  56]
 [ 48  48  17]
 [ 78  57 108]]


In [ ]:
print(a/b)

[[0.07142857 0.46666667 0.28571429]
 [0.1875     0.33333333 0.05882353]
 [0.46153846 0.15789474 0.33333333]]


In [ ]:
print(np.add(a,b))

[[15 22 18]
 [19 16 18]
 [19 22 24]]


In [ ]:
print(np.subtract(a,b))

[[-13  -8 -10]
 [-13  -8 -16]
 [ -7 -16 -12]]


In [ ]:
print(np.multiply(a,b))

[[ 14 105  56]
 [ 48  48  17]
 [ 78  57 108]]


In [ ]:
print(np.divide(a,b))

[[0.07142857 0.46666667 0.28571429]
 [0.1875     0.33333333 0.05882353]
 [0.46153846 0.15789474 0.33333333]]


array manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 5 5]
 [8 2 5]]
(2, 3)


Transpose

In [ ]:
x = np.random.randint(1,10,(2,3))
print(x)

[[9 1 2]
 [7 6 2]]


In [ ]:
print(np.transpose(x))

[[9 7]
 [1 6]
 [2 2]]


In [ ]:
x = np.random.randint(1,10,(2,3))
print(x)

[[6 5 4]
 [8 9 5]]


In [ ]:
trans_2 = x.T
print(trans_2)

[[6 8]
 [5 9]
 [4 5]]


reshape

In [ ]:
x = np.random.randint(1,10,(2,3))
print(x)

[[7 8 7]
 [1 8 4]]


In [ ]:
y = x.reshape(3,2)
print(y)

[[7 8]
 [7 1]
 [8 4]]


**PANDAS**

In [9]:
import pandas as pd

In [10]:
from sklearn.datasets import fetch_california_housing
california_df = fetch_california_housing()
type(california_df)

#pandas DataFrame
california_df = pd.DataFrame(california_df.data, columns=california_df.feature_names)
california_df.head()


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [11]:
california_df.shape

(20640, 8)

Exporting DataFrame to CSV

In [12]:
california_df.to_csv('california_housing_data.csv')

Exporting DataFrame to EXCEL

In [13]:
california_df.to_excel('california_housing_data.xlsx')

Importing CSV file to a Pandas DataFrame

In [16]:
california_df = pd.read_csv('/content/sample_data/california_housing_data.csv')
type(california_df)

pandas.core.frame.DataFrame

Importing EXCEL file to a Pandas DataFrame

In [18]:
california_df = pd.read_excel('/content/sample_data/california_housing_data.xlsx')
type(california_df)

pandas.core.frame.DataFrame

**DataFrame with random values**

In [19]:
import numpy as np
random_df = pd.DataFrame(np.random.rand(20,10))
random_df.head()

0         1         2         3         4         5         6  \
0  0.966864  0.984340  0.156176  0.066749  0.689838  0.807397  0.294916   
1  0.514819  0.981710  0.425329  0.504828  0.683029  0.242863  0.916412   
2  0.233154  0.136692  0.616173  0.247122  0.180372  0.891173  0.606250   
3  0.490360  0.667290  0.529688  0.308548  0.281963  0.666464  0.470540   
4  0.485843  0.705041  0.392452  0.231199  0.608583  0.464818  0.218642   

          7         8         9  
0  0.981539  0.949261  0.580445  
1  0.206475  0.757538  0.631046  
2  0.232218  0.041066  0.151459  
3  0.077014  0.370283  0.916955  
4  0.791042  0.264754  0.806257

In [20]:
random_df.shape

(20, 10)

**Find first 5 rows**

In [21]:
california_df.head()

Unnamed: 0  MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
0           0  8.3252        41  6.984127   1.023810         322  2.555556   
1           1  8.3014        21  6.238137   0.971880        2401  2.109842   
2           2  7.2574        52  8.288136   1.073446         496  2.802260   
3           3  5.6431        52  5.817352   1.073059         558  2.547945   
4           4  3.8462        52  6.281853   1.081081         565  2.181467   

   Latitude  Longitude  
0     37.88    -122.23  
1     37.86    -122.22  
2     37.85    -122.24  
3     37.85    -122.25  
4     37.85    -122.25

**Find last 5 rows**

In [22]:
california_df.tail()

Unnamed: 0  MedInc  HouseAge  AveRooms  AveBedrms  Population  \
20635       20635  1.5603        25  5.045455   1.133333         845   
20636       20636  2.5568        18  6.114035   1.315789         356   
20637       20637  1.7000        17  5.205543   1.120092        1007   
20638       20638  1.8672        18  5.329513   1.171920         741   
20639       20639  2.3886        16  5.254717   1.162264        1387   

       AveOccup  Latitude  Longitude  
20635  2.560606     39.48    -121.09  
20636  3.122807     39.49    -121.21  
20637  2.325635     39.43    -121.22  
20638  2.123209     39.43    -121.32  
20639  2.616981     39.37    -121.24

**Information about the DataFrame**

In [24]:
california_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  20640 non-null  int64  
 1   MedInc      20640 non-null  float64
 2   HouseAge    20640 non-null  int64  
 3   AveRooms    20640 non-null  float64
 4   AveBedrms   20640 non-null  float64
 5   Population  20640 non-null  int64  
 6   AveOccup    20640 non-null  float64
 7   Latitude    20640 non-null  float64
 8   Longitude   20640 non-null  float64
dtypes: float64(6), int64(3)
memory usage: 1.4 MB


**finding the number of missing values**

In [25]:
california_df.isnull().sum()

Unnamed: 0    0
MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

**Binary Classification Dataset Breast cancer**

In [30]:
from sklearn.datasets import load_breast_cancer
cancer_df = load_breast_cancer()
#convert to pandas DataFrame
cancer_df = pd.DataFrame(cancer_df.data, columns=cancer_df.feature_names)
cancer_df.head()
cancer_df['target'] = cancer_df.target
print(cancer_df['target'].value_counts())

AttributeError: 'DataFrame' object has no attribute 'target'

In [31]:
from sklearn.datasets import load_breast_cancer

cancer_data = load_breast_cancer() # rename the variable to avoid overwriting
#convert to pandas DataFrame
cancer_df = pd.DataFrame(cancer_data.data, columns=cancer_data.feature_names)
cancer_df.head()
cancer_df['target'] = cancer_data.target # access target from cancer_data
print(cancer_df['target'].value_counts())

target
1    357
0    212
Name: count, dtype: int64


In [32]:
cancer_df.groupby('target').mean()

mean radius  mean texture  mean perimeter   mean area  \
target                                                          
0         17.462830     21.604906      115.365377  978.376415   
1         12.146524     17.914762       78.075406  462.790196   

        mean smoothness  mean compactness  mean concavity  \
target                                                      
0              0.102898          0.145188        0.160775   
1              0.092478          0.080085        0.046058   

        mean concave points  mean symmetry  mean fractal dimension  ...  \
target                                                              ...   
0                  0.087990       0.192909                0.062680  ...   
1                  0.025717       0.174186                0.062867  ...   

        worst radius  worst texture  worst perimeter   worst area  \
target                                                              
0          21.134811      29.318208       141.370330  1422.286321   
1          13.379801      23.515070        87.005938   558.899440   

        worst smoothness  worst compactness  worst concavity  \
target                                                         
0               0.144845           0.374824         0.450606   
1               0.124959           0.182673         0.166238   

        worst concave points  worst symmetry  worst fractal dimension  
target                                                                 
0                   0.182237        0.323468                 0.091530  
1                   0.074444        0.270246                 0.079442  

[2 rows x 30 columns]