<a href="https://colab.research.google.com/github/DevSecOps-Stack/ML-Prerequisites/blob/main/ml_beginner_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [3]:
import numpy as np

array of zeros

In [4]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array of ones

In [5]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array of particular value

In [6]:
z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


identity matrix

In [7]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


create a numpy array with random values with floating values

In [8]:
b = np.random.random((3,4))
print(b)

[[0.11345409 0.8446311  0.89617234 0.89493543]
 [0.98984353 0.30761093 0.89435807 0.07843013]
 [0.39280069 0.32594745 0.7563898  0.19836285]]


create a numpy array with random values without floating values

In [9]:
c = np.random.randint(1,10,(3,4))
print(c)

[[4 9 5 4]
 [2 4 4 9]
 [5 7 5 3]]


create array evenly spaces values

In [10]:
d = np.linspace(1,10,6)
print(d)

[ 1.   2.8  4.6  6.4  8.2 10. ]


np.linspace(1, 10, 6):

This function creates a list of numbers starting from 1 and ending at 10.
It will create exactly 6 numbers, and these numbers will be evenly spread out between 1 and 10.
For example, if you want to go from 1 to 10 and stop at 6 points along the way, you get numbers that are evenly spaced.

print(d):

This command shows you the list of numbers that were created in the step above. note : above example starts with 1 and adds 1.8 till 10.

array of evenly spaces values specifying the step

In [11]:
e = np.arange(1,10,2)
print(e)

[1 3 5 7 9]


Creating an Array with np.arange():

np.arange(start, stop, step) is a function that generates a sequence of numbers within a specified range.
start: The first value in the sequence (here, it's 1).
stop: The upper bound of the sequence (here, it's 10). The sequence will not include this value.
step: The difference between consecutive numbers in the sequence (here, it's 2).
So, np.arange(1, 10, 2) creates an array containing the numbers: 1, 3, 5, 7, and 9.

Storing the Array: The resulting array is stored in the variable e.

Printing the Array: The line print(e) displays the contents of the array e on the console.

convert a list of numpy array

In [12]:
list_2 = [1,2,3,4]
np_array_2 = np.asarray(list_2)
print(np_array_2)
type(np_array_2)

[1 2 3 4]


numpy.ndarray

analysing the numpy array

In [13]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.shape)
print(c.ndim)

[[87 20 23 68 81]
 [64 30 71 79 85]
 [13 63 87 24 14]
 [12 87 69 56 48]
 [56 29 55 20 42]]
(5, 5)
2


number of elements in an array

In [14]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.size)

[[37 31 76 46 71]
 [43 52 64 39 83]
 [17 47 41 28 35]
 [12 75 87 58 52]
 [71 56 65 29 78]]
25


checking the datatypes of values in the array

In [15]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.dtype)

[[25 63 78 51 51]
 [81 47 61 17 67]
 [64 66 72 38 26]
 [32 45 53 69 37]
 [38 12 45 18 23]]
int64


math operations

In [16]:
list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]
print(list_1 + list_2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [17]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 5 4]
 [8 6 0]
 [5 2 2]]
[[16 18 12]
 [19 15 12]
 [11 15 14]]


In [18]:
print(a+b)

[[20 23 16]
 [27 21 12]
 [16 17 16]]


In [19]:
print(a-b)

[[-12 -13  -8]
 [-11  -9 -12]
 [ -6 -13 -12]]


In [20]:
print(a*b)

[[ 64  90  48]
 [152  90   0]
 [ 55  30  28]]


In [21]:
print(a/b)

[[0.25       0.27777778 0.33333333]
 [0.42105263 0.4        0.        ]
 [0.45454545 0.13333333 0.14285714]]


In [22]:
print(np.add(a,b))

[[20 23 16]
 [27 21 12]
 [16 17 16]]


In [ ]:
print(np.subtract(a,b))

[[-13  -8 -10]
 [-13  -8 -16]
 [ -7 -16 -12]]


In [ ]:
print(np.multiply(a,b))

[[ 14 105  56]
 [ 48  48  17]
 [ 78  57 108]]


In [23]:
print(np.divide(a,b))

[[0.25       0.27777778 0.33333333]
 [0.42105263 0.4        0.        ]
 [0.45454545 0.13333333 0.14285714]]


array manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 5 5]
 [8 2 5]]
(2, 3)


Transpose

In [ ]:
x = np.random.randint(1,10,(2,3))
print(x)

[[9 1 2]
 [7 6 2]]


In [ ]:
print(np.transpose(x))

[[9 7]
 [1 6]
 [2 2]]


In [ ]:
x = np.random.randint(1,10,(2,3))
print(x)

[[6 5 4]
 [8 9 5]]


In [ ]:
trans_2 = x.T
print(trans_2)

[[6 8]
 [5 9]
 [4 5]]


reshape

In [ ]:
x = np.random.randint(1,10,(2,3))
print(x)

[[7 8 7]
 [1 8 4]]


In [ ]:
y = x.reshape(3,2)
print(y)

[[7 8]
 [7 1]
 [8 4]]


**PANDAS**

In [35]:
import pandas as pd

In [25]:
from sklearn.datasets import fetch_california_housing
california_df = fetch_california_housing()
type(california_df)

#pandas DataFrame
california_df = pd.DataFrame(california_df.data, columns=california_df.feature_names)
california_df.head()


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [26]:
california_df.shape

(20640, 8)

Exporting DataFrame to CSV

In [ ]:
california_df.to_csv('california_housing_data.csv')

Exporting DataFrame to EXCEL

In [ ]:
california_df.to_excel('california_housing_data.xlsx')

Importing CSV file to a Pandas DataFrame

In [ ]:
california_df = pd.read_csv('/content/sample_data/california_housing_data.csv')
type(california_df)

pandas.core.frame.DataFrame

Importing EXCEL file to a Pandas DataFrame

In [ ]:
california_df = pd.read_excel('/content/sample_data/california_housing_data.xlsx')
type(california_df)

pandas.core.frame.DataFrame

**DataFrame with random values**

In [ ]:
import numpy as np
random_df = pd.DataFrame(np.random.rand(20,10))
random_df.head()

0         1         2         3         4         5         6  \
0  0.966864  0.984340  0.156176  0.066749  0.689838  0.807397  0.294916   
1  0.514819  0.981710  0.425329  0.504828  0.683029  0.242863  0.916412   
2  0.233154  0.136692  0.616173  0.247122  0.180372  0.891173  0.606250   
3  0.490360  0.667290  0.529688  0.308548  0.281963  0.666464  0.470540   
4  0.485843  0.705041  0.392452  0.231199  0.608583  0.464818  0.218642   

          7         8         9  
0  0.981539  0.949261  0.580445  
1  0.206475  0.757538  0.631046  
2  0.232218  0.041066  0.151459  
3  0.077014  0.370283  0.916955  
4  0.791042  0.264754  0.806257

In [ ]:
random_df.shape

(20, 10)

**Find first 5 rows**

In [30]:
california_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

**Find last 5 rows**

In [29]:
california_df.tail()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24

**Information about the DataFrame**

In [28]:
california_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


**finding the number of missing values**

In [ ]:
california_df.isnull().sum()

Unnamed: 0    0
MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

**Binary Classification Dataset Breast cancer**

In [41]:
from sklearn.datasets import load_breast_cancer
cancer_data = load_breast_cancer()
#convert to pandas DataFrame
cancer_df = pd.DataFrame(cancer_data.data, columns=cancer_data.feature_names)
cancer_df.head()
cancer_df['target'] = cancer_data.target
print(cancer_df['target'].value_counts())

target
1    357
0    212
Name: count, dtype: int64


In [43]:
cancer_df.groupby('target').mean()


mean radius  mean texture  mean perimeter   mean area  \
target                                                          
0         17.462830     21.604906      115.365377  978.376415   
1         12.146524     17.914762       78.075406  462.790196   

        mean smoothness  mean compactness  mean concavity  \
target                                                      
0              0.102898          0.145188        0.160775   
1              0.092478          0.080085        0.046058   

        mean concave points  mean symmetry  mean fractal dimension  ...  \
target                                                              ...   
0                  0.087990       0.192909                0.062680  ...   
1                  0.025717       0.174186                0.062867  ...   

        worst radius  worst texture  worst perimeter   worst area  \
target                                                              
0          21.134811      29.318208       141.370330  1422.286321   
1          13.379801      23.515070        87.005938   558.899440   

        worst smoothness  worst compactness  worst concavity  \
target                                                         
0               0.144845           0.374824         0.450606   
1               0.124959           0.182673         0.166238   

        worst concave points  worst symmetry  worst fractal dimension  
target                                                                 
0                   0.182237        0.323468                 0.091530  
1                   0.074444        0.270246                 0.079442  

[2 rows x 30 columns]

**STATISTICAL MEASURES**

Count no of values

In [44]:
cancer_df.count()

mean radius                569
mean texture               569
mean perimeter             569
mean area                  569
mean smoothness            569
mean compactness           569
mean concavity             569
mean concave points        569
mean symmetry              569
mean fractal dimension     569
radius error               569
texture error              569
perimeter error            569
area error                 569
smoothness error           569
compactness error          569
concavity error            569
concave points error       569
symmetry error             569
fractal dimension error    569
worst radius               569
worst texture              569
worst perimeter            569
worst area                 569
worst smoothness           569
worst compactness          569
worst concavity            569
worst concave points       569
worst symmetry             569
worst fractal dimension    569
target                     569
dtype: int64

Get mean value column wise

In [45]:
cancer_df.mean()

mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concavity              0.272188
worst concave points         0.114606
worst symmetry               0.290076
worst fractal dimension      0.083946
target                       0.627417
dtype: float64

standard deviation

In [46]:
cancer_df.std()

mean radius                  3.524049
mean texture                 4.301036
mean perimeter              24.298981
mean area                  351.914129
mean smoothness              0.014064
mean compactness             0.052813
mean concavity               0.079720
mean concave points          0.038803
mean symmetry                0.027414
mean fractal dimension       0.007060
radius error                 0.277313
texture error                0.551648
perimeter error              2.021855
area error                  45.491006
smoothness error             0.003003
compactness error            0.017908
concavity error              0.030186
concave points error         0.006170
symmetry error               0.008266
fractal dimension error      0.002646
worst radius                 4.833242
worst texture                6.146258
worst perimeter             33.602542
worst area                 569.356993
worst smoothness             0.022832
worst compactness            0.157336
worst concavity              0.208624
worst concave points         0.065732
worst symmetry               0.061867
worst fractal dimension      0.018061
target                       0.483918
dtype: float64

Min value and max values

In [49]:
cancer_df.min()
#cancer_df.max()

mean radius                  6.981000
mean texture                 9.710000
mean perimeter              43.790000
mean area                  143.500000
mean smoothness              0.052630
mean compactness             0.019380
mean concavity               0.000000
mean concave points          0.000000
mean symmetry                0.106000
mean fractal dimension       0.049960
radius error                 0.111500
texture error                0.360200
perimeter error              0.757000
area error                   6.802000
smoothness error             0.001713
compactness error            0.002252
concavity error              0.000000
concave points error         0.000000
symmetry error               0.007882
fractal dimension error      0.000895
worst radius                 7.930000
worst texture               12.020000
worst perimeter             50.410000
worst area                 185.200000
worst smoothness             0.071170
worst compactness            0.027290
worst concavity              0.000000
worst concave points         0.000000
worst symmetry               0.156500
worst fractal dimension      0.055040
target                       0.000000
dtype: float64

**All stats measure in one go**

In [50]:
cancer_df.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension      target  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

adding column price using target column values

In [52]:
cancer_df['price'] = cancer_df.target
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst perimeter  worst area  worst smoothness  \
0                 0.07871  ...           184.60      2019.0            0.1622   
1                 0.05667  ...           158.80      1956.0            0.1238   
2                 0.05999  ...           152.50      1709.0            0.1444   
3                 0.09744  ...            98.87       567.7            0.2098   
4                 0.05883  ...           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  target  price  
0                  0.11890       0      0  
1                  0.08902       0      0  
2                  0.08758       0      0  
3                  0.17300       0      0  
4                  0.07678       0      0  

[5 rows x 32 columns]

removing a raw

In [59]:
cancer_df = cancer_df.drop(index=0, axis=0)
cancer_df.head()

KeyError: '[0] not found in axis'