<a href="https://colab.research.google.com/github/DevSecOps-Stack/ML-Prerequisites/blob/main/ml_beginner_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [1]:
import numpy as np

array of zeros

In [3]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array of ones

In [5]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array of particular value

In [6]:
z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


identity matrix

In [8]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


create a numpy array with random values with floating values

In [10]:
b = np.random.random((3,4))
print(b)

[[0.14833147 0.01144511 0.26078043 0.5793363 ]
 [0.87165065 0.52476911 0.84878946 0.41335203]
 [0.22623399 0.42088161 0.68389723 0.16473441]]


create a numpy array with random values without floating values

In [12]:
c = np.random.randint(1,10,(3,4))
print(c)

[[2 8 9 9]
 [6 3 1 6]
 [3 7 6 8]]


create array evenly spaces values

In [14]:
d = np.linspace(1,10,6)
print(d)

[ 1.   2.8  4.6  6.4  8.2 10. ]


np.linspace(1, 10, 6):

This function creates a list of numbers starting from 1 and ending at 10.
It will create exactly 6 numbers, and these numbers will be evenly spread out between 1 and 10.
For example, if you want to go from 1 to 10 and stop at 6 points along the way, you get numbers that are evenly spaced.

print(d):

This command shows you the list of numbers that were created in the step above. note : above example starts with 1 and adds 1.8 till 10.

array of evenly spaces values specifying the step

In [16]:
e = np.arange(1,10,2)
print(e)

[1 3 5 7 9]


Creating an Array with np.arange():

np.arange(start, stop, step) is a function that generates a sequence of numbers within a specified range.
start: The first value in the sequence (here, it's 1).
stop: The upper bound of the sequence (here, it's 10). The sequence will not include this value.
step: The difference between consecutive numbers in the sequence (here, it's 2).
So, np.arange(1, 10, 2) creates an array containing the numbers: 1, 3, 5, 7, and 9.

Storing the Array: The resulting array is stored in the variable e.

Printing the Array: The line print(e) displays the contents of the array e on the console.

convert a list of numpy array

In [20]:
list_2 = [1,2,3,4]
np_array_2 = np.asarray(list_2)
print(np_array_2)
type(np_array_2)

[1 2 3 4]


numpy.ndarray

analysing the numpy array

In [26]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.shape)
print(c.ndim)

[[21 39 70 31 20]
 [55 83 40 68 31]
 [37 38 76 14 81]
 [61 44 29 47 44]
 [87 21 41 58 57]]
(5, 5)
2


number of elements in an array

In [27]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.size)

[[79 51 82 43 31]
 [80 38 29 38 65]
 [87 64 66 73 32]
 [70 10 24 13 84]
 [51 38 56 30 40]]
25


checking the datatypes of values in the array

In [28]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.dtype)

[[69 21 18 26 31]
 [67 37 77 60 10]
 [75 11 47 61 57]
 [42 82 64 89 51]
 [42 54 87 85 49]]
int64


math operations

In [29]:
list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]
print(list_1 + list_2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [30]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 7 4]
 [3 4 1]
 [6 3 6]]
[[14 15 14]
 [16 12 17]
 [13 19 18]]


In [31]:
print(a+b)

[[15 22 18]
 [19 16 18]
 [19 22 24]]


In [32]:
print(a-b)

[[-13  -8 -10]
 [-13  -8 -16]
 [ -7 -16 -12]]


In [33]:
print(a*b)

[[ 14 105  56]
 [ 48  48  17]
 [ 78  57 108]]


In [34]:
print(a/b)

[[0.07142857 0.46666667 0.28571429]
 [0.1875     0.33333333 0.05882353]
 [0.46153846 0.15789474 0.33333333]]


In [35]:
print(np.add(a,b))

[[15 22 18]
 [19 16 18]
 [19 22 24]]


In [36]:
print(np.subtract(a,b))

[[-13  -8 -10]
 [-13  -8 -16]
 [ -7 -16 -12]]


In [37]:
print(np.multiply(a,b))

[[ 14 105  56]
 [ 48  48  17]
 [ 78  57 108]]


In [38]:
print(np.divide(a,b))

[[0.07142857 0.46666667 0.28571429]
 [0.1875     0.33333333 0.05882353]
 [0.46153846 0.15789474 0.33333333]]


array manipulation

In [40]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 5 5]
 [8 2 5]]
(2, 3)


Transpose

In [41]:
x = np.random.randint(1,10,(2,3))
print(x)

[[9 1 2]
 [7 6 2]]


In [42]:
print(np.transpose(x))

[[9 7]
 [1 6]
 [2 2]]


In [45]:
x = np.random.randint(1,10,(2,3))
print(x)

[[6 5 4]
 [8 9 5]]


In [46]:
trans_2 = x.T
print(trans_2)

[[6 8]
 [5 9]
 [4 5]]


reshape

In [47]:
x = np.random.randint(1,10,(2,3))
print(x)

[[7 8 7]
 [1 8 4]]


In [48]:
y = x.reshape(3,2)
print(y)

[[7 8]
 [7 1]
 [8 4]]
